language: python

cache: pip

git:
  depth: 1

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  include:
    - stage: build
      name: "Build openshift-acs distro"
      before_install:
        - gem install asciidoctor
        - gem install asciidoctor-diagram
      install:
        - pip3 install pyyaml
        - pip3 install aura.tar.gz
      script:
        - python3 build.py --distro openshift-acs --product "Red Hat Advanced Cluster Security for Kubernetes" --version 3.73 --no-upstream-fetch && python3 makeBuild.py
    - stage: check-with-vale
      env:
        - CAN_FAIL=true
      if: type IN (pull_request)
      name: "Run Vale against PR asciidoc files"
      language: minimal
      before_script:
        - gem install asciidoctor
      script:
        - travis_retry wget https://github.com/errata-ai/vale/releases/download/v2.20.1/vale_2.20.1_Linux_64-bit.tar.gz --retry-connrefused
        - mkdir bin && tar -xvzf vale_2.20.1_Linux_64-bit.tar.gz -C bin
        - export PATH=./bin:"$PATH"
        - travis_retry vale sync # pull down VRH rules package
        - chmod +x ./scripts/check-with-vale.sh
        - ./scripts/check-with-vale.sh
    # Commenting out to disable auto-merging of PRs
    # - stage: automerge
    #   if: env(PR_AUTHOR)=openshift-cherrypick-robot
    #   script: bash ./automerge.sh
    - stage: netlify
      name: "Create Netlify preiview"
      env:
        - CAN_FAIL=true
      language: minimal
      if: branch IN (rhacs-docs, rhacs-docs-3.74, rhacs-docs-3.73, rhacs-docs-3.72, rhacs-docs-3.71)
      script:
        - chmod +x autopreview.sh && ./autopreview.sh

stages:
  - build
  - check-with-vale
  - netlify
